dist: xenial

language: cpp

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - wget
      - coreutils
      - pkg-config

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq liblua5.1-0-dev
  - wget https://github.com/bazelbuild/bazel/releases/download/0.11.0/bazel_0.11.0-linux-x86_64.deb
  - sudo dpkg -i bazel_0.11.0-linux-x86_64.deb

script:
  - bazel build //...
  - bazel test //... --test_output=streamed
