cc_library(
  name = 'libconfig',
  srcs = [
    'config.cc',
  ],
  hdrs = [
    'config.h',
  ],
  deps = [
    '//lib/context:libcomponent',
    '//lib/context:libcontext',
    '//lib/log:liblog',
    '//lib/log:liblog_raw',
    '//lib/log:liblog_file',
    '//protos/lib/config:libconfig_cc_proto',
  ],
  visibility = ['//visibility:public'],
)
